"""add profile experience and interests

Revision ID: 980cef234a43
Revises: ccb9b9813cb6
Create Date: 2026-09-11 13:04:09.226589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980cef234a43'
down_revision: Union[str, Sequence[str], None] = 'ccb9b9813cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_project_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('project_interests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('project_interests')
        batch_op.drop_column('interests')
        batch_op.drop_column('raw_project_experience')

    # ### end Alembic commands ###
