"""initial_schema

Revision ID: ccb9b9813cb6
Revises: 
Create Date: 2026-09-11 12:29:44.869833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb9b9813cb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('parent_skill_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_skills_parent_skill_id'), ['parent_skill_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('year_of_study', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('PROFILE_CREATED', 'SKILL_ADDED', 'LEARNING_GOAL_SET', 'MATCH_GENERATED', 'SESSION_SCHEDULED', 'SESSION_COMPLETED', 'CREDIT_TRANSFERRED', 'PROJECT_CREATED', 'TEAM_FORMED', name='activityeventtype', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_student_id'), ['student_id'], unique=False)

    op.create_table('availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek', native_enum=False, length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilities_student_id'), ['student_id'], unique=False)

    op.create_table('learning_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('target_proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False, length=20), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'ACHIEVED', name='goalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_goals_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_goals_student_id'), ['student_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'COMPLETED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('skill_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('assessor_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('proficiency_awarded', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False, length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['student_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_assessments_assessor_id'), ['assessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_assessments_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_assessments_student_id'), ['student_id'], unique=False)

    op.create_table('skill_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'DECLINED', 'COMPLETED', name='matchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_matches_learner_student_id'), ['learner_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_matches_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_matches_teacher_student_id'), ['teacher_student_id'], unique=False)

    op.create_table('student_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('TEACH', 'LEARN', name='skilldirection', native_enum=False, length=10), nullable=False),
    sa.Column('proficiency_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False, length=20), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_skills_student_id'), ['student_id'], unique=False)

    op.create_table('teaching_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_student_id', sa.String(length=36), nullable=False),
    sa.Column('learner_student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_sessions_learner_student_id'), ['learner_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_sessions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_sessions_teacher_student_id'), ['teacher_student_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('learned_summary', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_learning_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('project_skill_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('required_proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False, length=20), nullable=False),
    sa.Column('importance', sa.Enum('MANDATORY', 'PREFERRED', name='requirementimportance', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_skill_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_skill_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_skill_requirements_skill_id'), ['skill_id'], unique=False)

    op.create_table('skill_credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_student_id', sa.String(length=36), nullable=True),
    sa.Column('to_student_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INITIAL_GRANT', 'SESSION_TRANSFER', 'REWARD', 'BONUS', name='credittransactiontype', native_enum=False, length=30), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_student_id'], ['student_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_credit_transactions_from_student_id'), ['from_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_credit_transactions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_credit_transactions_to_student_id'), ['to_student_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('FORMING', 'ACTIVE', 'COMPLETED', name='teamstatus', native_enum=False, length=20), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_project_id'), ['project_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('LEAD', 'DEVELOPER', 'DESIGNER', 'RESEARCHER', 'CONTRIBUTOR', name='teamrole', native_enum=False, length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_student_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_project_id'))

    op.drop_table('teams')
    with op.batch_alter_table('skill_credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_credit_transactions_to_student_id'))
        batch_op.drop_index(batch_op.f('ix_skill_credit_transactions_session_id'))
        batch_op.drop_index(batch_op.f('ix_skill_credit_transactions_from_student_id'))

    op.drop_table('skill_credit_transactions')
    with op.batch_alter_table('project_skill_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_skill_requirements_skill_id'))
        batch_op.drop_index(batch_op.f('ix_project_skill_requirements_project_id'))

    op.drop_table('project_skill_requirements')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_learning_sessions_session_id'))

    op.drop_table('learning_sessions')
    with op.batch_alter_table('teaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_sessions_teacher_student_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_sessions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_sessions_learner_student_id'))

    op.drop_table('teaching_sessions')
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_skills_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_skills_skill_id'))

    op.drop_table('student_skills')
    with op.batch_alter_table('skill_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_matches_teacher_student_id'))
        batch_op.drop_index(batch_op.f('ix_skill_matches_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_matches_learner_student_id'))

    op.drop_table('skill_matches')
    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_assessments_student_id'))
        batch_op.drop_index(batch_op.f('ix_skill_assessments_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_assessments_assessor_id'))

    op.drop_table('skill_assessments')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_goals_student_id'))
        batch_op.drop_index(batch_op.f('ix_learning_goals_skill_id'))

    op.drop_table('learning_goals')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilities_student_id'))

    op.drop_table('availabilities')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_student_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_parent_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    # ### end Alembic commands ###
