"""
Comprehensive Campus Seed Data for AI Skill Exchange
Contains 55+ Skills across 13 categories and 32 realistic student profiles.
"""

SKILLS_SEED = [
    # 1. Programming
    {
        "name": "Python",
        "category": "Programming",
        "description": "High-level programming language emphasizing readability and vast library ecosystem.",
        "aliases": "py, python3",
        "parent_name": None,
    },
    {
        "name": "JavaScript",
        "category": "Programming",
        "description": "Dynamic script language powering modern client-side and full-stack web development.",
        "aliases": "js, es6, ecmascript",
        "parent_name": None,
    },
    {
        "name": "TypeScript",
        "category": "Programming",
        "description": "Typed superset of JavaScript that compiles to plain JavaScript.",
        "aliases": "ts",
        "parent_name": "JavaScript",
    },
    {
        "name": "Rust",
        "category": "Programming",
        "description": "Systems programming language focused on memory safety, concurrency, and performance.",
        "aliases": "rustlang",
        "parent_name": None,
    },
    {
        "name": "Go",
        "category": "Programming",
        "description": "Open-source compiled language designed by Google for scalable concurrent backend services.",
        "aliases": "golang",
        "parent_name": None,
    },
    {
        "name": "C++",
        "category": "Programming",
        "description": "High-performance systems programming language with generic and object-oriented features.",
        "aliases": "cpp",
        "parent_name": None,
    },
    {
        "name": "Java",
        "category": "Programming",
        "description": "Enterprise-grade class-based, object-oriented language for robust cross-platform applications.",
        "aliases": "jvm, java21",
        "parent_name": None,
    },
    {
        "name": "C#",
        "category": "Programming",
        "description": "Modern type-safe object-oriented language developed by Microsoft for .NET and Unity.",
        "aliases": "csharp, dotnet",
        "parent_name": None,
    },

    # 2. AI/ML
    {
        "name": "Machine Learning",
        "category": "AI/ML",
        "description": "Study and construction of algorithms that learn from data and make predictions.",
        "aliases": "ml, statistical learning",
        "parent_name": None,
    },
    {
        "name": "Deep Learning",
        "category": "AI/ML",
        "description": "Neural network architectures including CNNs, RNNs, and Transformers.",
        "aliases": "dl, neural networks",
        "parent_name": "Machine Learning",
    },
    {
        "name": "Natural Language Processing",
        "category": "AI/ML",
        "description": "Techniques allowing computers to understand, interpret, and generate human language.",
        "aliases": "nlp, computational linguistics",
        "parent_name": "Machine Learning",
    },
    {
        "name": "Computer Vision",
        "category": "AI/ML",
        "description": "Algorithms enabling digital systems to extract high-level information from images and video.",
        "aliases": "cv, image processing",
        "parent_name": "Machine Learning",
    },
    {
        "name": "Prompt Engineering",
        "category": "AI/ML",
        "description": "Designing effective prompts, few-shot examples, and chain-of-thought workflows for LLMs.",
        "aliases": "in-context learning, llm prompts",
        "parent_name": None,
    },
    {
        "name": "Reinforcement Learning",
        "category": "AI/ML",
        "description": "Training intelligent agents to make sequences of decisions by maximizing cumulative reward.",
        "aliases": "rl, q-learning, policy gradients",
        "parent_name": "Machine Learning",
    },

    # 3. Data Science
    {
        "name": "Data Analysis",
        "category": "Data Science",
        "description": "Inspecting, cleansing, transforming, and modeling data to discover useful insights.",
        "aliases": "exploratory data analysis, eda",
        "parent_name": None,
    },
    {
        "name": "Pandas & NumPy",
        "category": "Data Science",
        "description": "Fundamental Python libraries for numerical matrix computing and data manipulation.",
        "aliases": "pandas, numpy, vectorization",
        "parent_name": "Data Analysis",
    },
    {
        "name": "Data Visualization",
        "category": "Data Science",
        "description": "Creating clear visual representations of data patterns using tools like Matplotlib, Seaborn, D3.",
        "aliases": "dataviz, charts, dashboarding",
        "parent_name": "Data Analysis",
    },
    {
        "name": "SQL & Relational Modeling",
        "category": "Data Science",
        "description": "Structured Query Language for relational database querying, joins, window functions, and indexing.",
        "aliases": "sql, rdbms, postgresql querying",
        "parent_name": None,
    },
    {
        "name": "Statistical Inference",
        "category": "Data Science",
        "description": "Hypothesis testing, p-values, confidence intervals, and Bayesian updating.",
        "aliases": "biostatistics, inferential statistics",
        "parent_name": None,
    },

    # 4. Web Development
    {
        "name": "React.js",
        "category": "Web Development",
        "description": "Declarative component-based frontend library for interactive single-page user interfaces.",
        "aliases": "react, reactjs",
        "parent_name": None,
    },
    {
        "name": "Next.js",
        "category": "Web Development",
        "description": "Full-stack React framework providing SSR, App Router, API routes, and static generation.",
        "aliases": "nextjs, next",
        "parent_name": "React.js",
    },
    {
        "name": "FastAPI",
        "category": "Web Development",
        "description": "Modern, fast, asynchronous Python web framework for building high-concurrency REST APIs.",
        "aliases": "fastapi, pydantic web",
        "parent_name": "Python",
    },
    {
        "name": "Node.js",
        "category": "Web Development",
        "description": "V8 asynchronous event-driven JavaScript runtime for server-side networking.",
        "aliases": "nodejs, expressjs",
        "parent_name": "JavaScript",
    },
    {
        "name": "Django",
        "category": "Web Development",
        "description": "Batteries-included Python web framework prioritizing rapid development and clean design.",
        "aliases": "django rest framework, drf",
        "parent_name": "Python",
    },
    {
        "name": "Tailwind CSS",
        "category": "Web Development",
        "description": "Utility-first CSS framework for rapid bespoke responsive interface composition.",
        "aliases": "tailwind, utility css",
        "parent_name": None,
    },
    {
        "name": "GraphQL",
        "category": "Web Development",
        "description": "Query language and runtime for APIs allowing clients to request exact fields needed.",
        "aliases": "graphql api, apollo",
        "parent_name": None,
    },

    # 5. Mobile Development
    {
        "name": "React Native",
        "category": "Mobile Development",
        "description": "Framework for authoring native iOS and Android apps using React and TypeScript.",
        "aliases": "rn, expo",
        "parent_name": "React.js",
    },
    {
        "name": "Flutter",
        "category": "Mobile Development",
        "description": "Google cross-platform UI toolkit using Dart for compiling native mobile and desktop apps.",
        "aliases": "dart flutter",
        "parent_name": None,
    },
    {
        "name": "iOS / Swift",
        "category": "Mobile Development",
        "description": "Native Apple platform development using Swift and SwiftUI frameworks.",
        "aliases": "swiftui, apple ios",
        "parent_name": None,
    },
    {
        "name": "Android / Kotlin",
        "category": "Mobile Development",
        "description": "Native Android app engineering utilizing Kotlin and Jetpack Compose.",
        "aliases": "kotlin android, jetpack compose",
        "parent_name": None,
    },

    # 6. Cloud
    {
        "name": "AWS Cloud Architecture",
        "category": "Cloud",
        "description": "Designing highly scalable, fault-tolerant infrastructure using Amazon Web Services (EC2, S3, RDS).",
        "aliases": "aws, amazon web services",
        "parent_name": None,
    },
    {
        "name": "Google Cloud Platform",
        "category": "Cloud",
        "description": "Cloud computing services covering BigQuery, Cloud Run, Vertex AI, and Compute Engine.",
        "aliases": "gcp, google cloud",
        "parent_name": None,
    },
    {
        "name": "Microsoft Azure",
        "category": "Cloud",
        "description": "Enterprise cloud services including Azure App Service, CosmosDB, and Azure DevOps.",
        "aliases": "azure",
        "parent_name": None,
    },
    {
        "name": "Serverless Computing",
        "category": "Cloud",
        "description": "Event-driven execution architecture using AWS Lambda, Cloud Functions, and edge workers.",
        "aliases": "faas, lambda",
        "parent_name": "AWS Cloud Architecture",
    },

    # 7. Cybersecurity
    {
        "name": "Network Security",
        "category": "Cybersecurity",
        "description": "Protocols, firewalls, intrusion detection, packet analysis, and secure routing.",
        "aliases": "wireshark, firewalls, tcp/ip security",
        "parent_name": None,
    },
    {
        "name": "Ethical Hacking & Penetration Testing",
        "category": "Cybersecurity",
        "description": "Systematic vulnerability assessment, exploit verification, and security auditing.",
        "aliases": "pentesting, red teaming, oscp",
        "parent_name": None,
    },
    {
        "name": "Cryptography Fundamentals",
        "category": "Cybersecurity",
        "description": "Symmetric/asymmetric encryption, hashing, digital signatures, and public key infrastructure.",
        "aliases": "rsa, aes, pki, zero knowledge",
        "parent_name": None,
    },
    {
        "name": "Web Application Security",
        "category": "Cybersecurity",
        "description": "Mitigating OWASP Top 10 vulnerabilities: XSS, SQLi, CSRF, SSRF, and auth bypasses.",
        "aliases": "owasp, secure coding",
        "parent_name": None,
    },

    # 8. UI/UX
    {
        "name": "UI Design & Wireframing",
        "category": "UI/UX",
        "description": "Crafting visual hierarchies, responsive grid layouts, color systems, and micro-interactions.",
        "aliases": "visual design, wireframes",
        "parent_name": None,
    },
    {
        "name": "UX User Research",
        "category": "UI/UX",
        "description": "User interviews, usability testing, journey mapping, personas, and heuristic evaluations.",
        "aliases": "user testing, empathy mapping",
        "parent_name": None,
    },
    {
        "name": "Figma Prototyping",
        "category": "UI/UX",
        "description": "Advanced Figma auto-layout, interactive components, tokens, and clickable prototypes.",
        "aliases": "figma, prototyping",
        "parent_name": "UI Design & Wireframing",
    },
    {
        "name": "Design Systems",
        "category": "UI/UX",
        "description": "Building unified, accessible component libraries and design tokens across platforms.",
        "aliases": "component libraries, atomic design",
        "parent_name": "UI Design & Wireframing",
    },

    # 9. DevOps
    {
        "name": "Docker Containerization",
        "category": "DevOps",
        "description": "Building reproducible lightweight container images, multi-stage builds, and compose stacks.",
        "aliases": "docker, containers",
        "parent_name": None,
    },
    {
        "name": "Kubernetes Orchestration",
        "category": "DevOps",
        "description": "Automated deployment, scaling, service meshes, and management of containerized apps.",
        "aliases": "k8s, helm",
        "parent_name": "Docker Containerization",
    },
    {
        "name": "CI/CD Pipelines",
        "category": "DevOps",
        "description": "Automated testing, linting, build pipelines, and zero-downtime production deployment.",
        "aliases": "github actions, gitlab ci",
        "parent_name": None,
    },
    {
        "name": "Infrastructure as Code (Terraform)",
        "category": "DevOps",
        "description": "Provisioning and managing cloud infrastructure via declarative configuration files.",
        "aliases": "terraform, iac",
        "parent_name": None,
    },

    # 10. Business
    {
        "name": "Product Management",
        "category": "Business",
        "description": "Defining product vision, writing PRDs, roadmapping, metrics tracking, and sprint planning.",
        "aliases": "pm, product roadmap",
        "parent_name": None,
    },
    {
        "name": "Financial Modeling",
        "category": "Business",
        "description": "Constructing pro-forma financial statements, cash flow forecasts, and unit economics.",
        "aliases": "dcf, valuation, excel modeling",
        "parent_name": None,
    },
    {
        "name": "Venture Capital & Pitching",
        "category": "Business",
        "description": "Structuring investor pitch decks, valuation negotiations, and startup fundraising.",
        "aliases": "pitch decks, fundraising",
        "parent_name": None,
    },
    {
        "name": "Agile & Scrum Project Management",
        "category": "Business",
        "description": "Facilitating sprint retrospectives, backlog grooming, kanban workflows, and team velocity.",
        "aliases": "scrum, agile, jira",
        "parent_name": None,
    },

    # 11. Agriculture
    {
        "name": "Precision Agriculture & Drones",
        "category": "Agriculture",
        "description": "Using multispectral drone imagery, GPS guidance, and variable rate technology for crop yield.",
        "aliases": "drone mapping, precision farming",
        "parent_name": None,
    },
    {
        "name": "Hydroponics & Vertical Farming",
        "category": "Agriculture",
        "description": "Soilless nutrient-film cultivation, controlled environment agriculture (CEA), and LED spectrums.",
        "aliases": "hydroponics, aquaponics, vertical farming",
        "parent_name": None,
    },
    {
        "name": "Soil Health & Organic Farming",
        "category": "Agriculture",
        "description": "Microbiome enrichment, cover cropping, compost teas, and sustainable regenerative soil practices.",
        "aliases": "soil microbiology, regenerative agriculture",
        "parent_name": None,
    },
    {
        "name": "Agri-Tech IoT Monitoring",
        "category": "Agriculture",
        "description": "Deploying LoRaWAN soil moisture probes, automated drip valves, and weather station telemetry.",
        "aliases": "smart agriculture, agri iot",
        "parent_name": None,
    },

    # 12. Research
    {
        "name": "Scientific Paper Writing",
        "category": "Research",
        "description": "Structuring academic manuscripts, peer-review correspondence, citations, and IEEE/ACM formatting.",
        "aliases": "academic writing, latex paper",
        "parent_name": None,
    },
    {
        "name": "Qualitative Research Methods",
        "category": "Research",
        "description": "Ethnographic observation, thematic coding, grounded theory, and focus group moderation.",
        "aliases": "qualitative analysis, coding interviews",
        "parent_name": None,
    },
    {
        "name": "Experimental Design & A/B Testing",
        "category": "Research",
        "description": "Formulating randomized controlled experiments, sample size power calculations, and variant testing.",
        "aliases": "ab testing, randomized control trials",
        "parent_name": None,
    },
    {
        "name": "Literature Review Synthesis",
        "category": "Research",
        "description": "Systematic literature search protocols, meta-analysis, and gap identification.",
        "aliases": "systematic review, meta analysis",
        "parent_name": None,
    },

    # 13. Communication
    {
        "name": "Technical Writing",
        "category": "Communication",
        "description": "Authoring developer documentation, API references, architecture decision records, and tutorials.",
        "aliases": "tech docs, api docs",
        "parent_name": None,
    },
    {
        "name": "Public Speaking & Pitch Presentation",
        "category": "Communication",
        "description": "Stage presence, vocal delivery, slide narrative storytelling, and hackathon presentation skills.",
        "aliases": "pitching, stage speaking",
        "parent_name": None,
    },
    {
        "name": "Cross-functional Team Leadership",
        "category": "Communication",
        "description": "Aligning engineers, designers, and domain specialists toward collective deadlines.",
        "aliases": "engineering management, team coaching",
        "parent_name": None,
    },
    {
        "name": "Negotiation & Conflict Resolution",
        "category": "Communication",
        "description": "Principled negotiation, mediation, interest-based bargaining, and productive team debates.",
        "aliases": "mediation, debate",
        "parent_name": None,
    },
]

STUDENTS_SEED = [
    {
        "email": "aarav.sharma@university.edu",
        "name": "Aarav Sharma",
        "dept": "Computer Science",
        "year": "Junior",
        "bio": "Full-stack builder passionate about open source and distributed systems. Built campus club platform.",
        "github": "https://github.com/aarav-sharma",
        "teach": [
            {"skill": "Python", "level": "EXPERT", "exp": 3.5, "desc": "Led Python workshop for 150 freshmen; built high-throughput scrapers."},
            {"skill": "FastAPI", "level": "ADVANCED", "exp": 2.0, "desc": "Authored production REST APIs with async SQLAlchemy."},
            {"skill": "Docker Containerization", "level": "INTERMEDIATE", "exp": 1.5, "desc": "Containerizing web services with multi-stage caching."},
        ],
        "learn": [
            {"skill": "React Native", "level": "BEGINNER", "desc": "Want to build iOS and Android apps for campus hackathon project."},
            {"skill": "Kubernetes Orchestration", "level": "BEGINNER", "desc": "Looking to master cluster deployments and Helm charts."},
        ],
    },
    {
        "email": "priya.patel@university.edu",
        "name": "Priya Patel",
        "dept": "Data Science",
        "year": "Senior",
        "bio": "NLP researcher studying low-resource language processing and transformer architectures.",
        "github": "https://github.com/priyapatel-ds",
        "teach": [
            {"skill": "Natural Language Processing", "level": "ADVANCED", "exp": 2.5, "desc": "Fine-tuned BERT and Llama models on multilingual corpora."},
            {"skill": "Machine Learning", "level": "ADVANCED", "exp": 3.0, "desc": "Teaching assistant for undergraduate Intro to ML."},
            {"skill": "Pandas & NumPy", "level": "EXPERT", "exp": 4.0, "desc": "Extensive data cleaning and vectorized pipeline authoring."},
        ],
        "learn": [
            {"skill": "TypeScript", "level": "BEGINNER", "desc": "Want to build interactive frontend demos for my ML models."},
            {"skill": "Next.js", "level": "BEGINNER", "desc": "Learning to create server-rendered research portals."},
        ],
    },
    {
        "email": "marcus.vance@university.edu",
        "name": "Marcus Vance",
        "dept": "Human-Computer Interaction",
        "year": "Junior",
        "bio": "Product designer obsessed with accessible typography, micro-interactions, and design systems.",
        "github": "https://github.com/marcusvance-design",
        "teach": [
            {"skill": "Figma Prototyping", "level": "EXPERT", "exp": 3.0, "desc": "Designed university mobile app UI; created comprehensive token library."},
            {"skill": "UI Design & Wireframing", "level": "ADVANCED", "exp": 2.5, "desc": "Expert in visual hierarchy and responsive wireframing."},
            {"skill": "UX User Research", "level": "ADVANCED", "exp": 2.0, "desc": "Conducted 40+ user interviews and usability labs."},
        ],
        "learn": [
            {"skill": "Tailwind CSS", "level": "BEGINNER", "desc": "Want to turn my Figma designs into real web code myself."},
            {"skill": "React.js", "level": "BEGINNER", "desc": "Eager to understand how components consume design tokens."},
        ],
    },
    {
        "email": "elena.rostova@university.edu",
        "name": "Elena Rostova",
        "dept": "Computer Science",
        "year": "Sophomore",
        "bio": "Frontend enthusiast loving React and Tailwind. Winner of HackUni 2025 best UI prize.",
        "github": "https://github.com/elena-rostova",
        "teach": [
            {"skill": "React.js", "level": "ADVANCED", "exp": 2.0, "desc": "Built 10+ single-page apps with custom hooks and state management."},
            {"skill": "Tailwind CSS", "level": "ADVANCED", "exp": 2.0, "desc": "Tailwind wizard with custom config, responsive grids, and animations."},
            {"skill": "JavaScript", "level": "ADVANCED", "exp": 2.5, "desc": "Solid understanding of closures, async/await, and DOM APIs."},
        ],
        "learn": [
            {"skill": "Python", "level": "BEGINNER", "desc": "Want to learn backend development and connect to AI services."},
            {"skill": "FastAPI", "level": "BEGINNER", "desc": "Looking for a mentor to teach modern Python REST backends."},
        ],
    },
    {
        "email": "tariq.mansoor@university.edu",
        "name": "Tariq Mansoor",
        "dept": "Cybersecurity",
        "year": "Senior",
        "bio": "Capture the Flag (CTF) competitor and security researcher. Lead of campus CyberSec club.",
        "github": "https://github.com/tariq-sec",
        "teach": [
            {"skill": "Ethical Hacking & Penetration Testing", "level": "EXPERT", "exp": 3.0, "desc": "Ranked top 1% on HackTheBox; found 3 CVEs in open source tools."},
            {"skill": "Web Application Security", "level": "ADVANCED", "exp": 2.5, "desc": "Taught OWASP security auditing to student engineering teams."},
            {"skill": "Network Security", "level": "ADVANCED", "exp": 3.0, "desc": "Wireshark packet forensic analysis and iptables configuration."},
        ],
        "learn": [
            {"skill": "Rust", "level": "BEGINNER", "desc": "Want to build memory-safe exploit analysis tools."},
            {"skill": "AWS Cloud Architecture", "level": "INTERMEDIATE", "desc": "Targeting cloud security architecture for graduation."},
        ],
    },
    {
        "email": "ananya.iyer@university.edu",
        "name": "Ananya Iyer",
        "dept": "Agricultural Engineering",
        "year": "Masters",
        "bio": "Working on smart irrigation and precision agriculture using IoT sensor networks.",
        "github": "https://github.com/ananya-agritech",
        "teach": [
            {"skill": "Precision Agriculture & Drones", "level": "EXPERT", "exp": 3.5, "desc": "Conducted drone multispectral NDVI mapping for 500-acre farm."},
            {"skill": "Agri-Tech IoT Monitoring", "level": "ADVANCED", "exp": 2.0, "desc": "Built LoRaWAN soil moisture mesh telemetry networks."},
            {"skill": "Soil Health & Organic Farming", "level": "ADVANCED", "exp": 4.0, "desc": "Published paper on regenerative soil microbial diversity."},
        ],
        "learn": [
            {"skill": "Computer Vision", "level": "BEGINNER", "desc": "Need to train automated weed and crop disease detection models."},
            {"skill": "Data Visualization", "level": "INTERMEDIATE", "desc": "Want to build web dashboards for farm telemetry sensors."},
        ],
    },
    {
        "email": "chen.wei@university.edu",
        "name": "Chen Wei",
        "dept": "Computer Science",
        "year": "PhD",
        "bio": "Computer vision researcher focusing on real-time edge segmentation and object detection.",
        "github": "https://github.com/chenwei-vision",
        "teach": [
            {"skill": "Computer Vision", "level": "EXPERT", "exp": 5.0, "desc": "CVPR co-author; trained real-time YOLO and SAM models for robotics."},
            {"skill": "Deep Learning", "level": "EXPERT", "exp": 4.5, "desc": "PyTorch expert in custom loss functions and CUDA optimization."},
            {"skill": "C++", "level": "ADVANCED", "exp": 4.0, "desc": "High-performance inference engine acceleration with TensorRT."},
        ],
        "learn": [
            {"skill": "Agri-Tech IoT Monitoring", "level": "BEGINNER", "desc": "Want to apply edge CV models to agricultural drone feeds."},
            {"skill": "Precision Agriculture & Drones", "level": "BEGINNER", "desc": "Collaborating on agricultural research grant."},
        ],
    },
    {
        "email": "samuel.ochieng@university.edu",
        "name": "Samuel Ochieng",
        "dept": "Business & Entrepreneurship",
        "year": "Junior",
        "bio": "Student startup founder. Raised $15K university seed grant. Passionate about product-market fit.",
        "github": "https://github.com/sam-ochieng-pm",
        "teach": [
            {"skill": "Product Management", "level": "ADVANCED", "exp": 2.5, "desc": "Led 3 student software products from discovery to launch."},
            {"skill": "Venture Capital & Pitching", "level": "ADVANCED", "exp": 2.0, "desc": "Pitch coach for campus accelerator; won 2 pitch competitions."},
            {"skill": "Public Speaking & Pitch Presentation", "level": "EXPERT", "exp": 3.0, "desc": "Keynote speaker at campus tech summit; TEDx youth speaker."},
        ],
        "learn": [
            {"skill": "SQL & Relational Modeling", "level": "BEGINNER", "desc": "Want to query product analytics and user retention directly."},
            {"skill": "Python", "level": "BEGINNER", "desc": "Want to automate startup workflow scripts."},
        ],
    },
    {
        "email": "fatima.almansoori@university.edu",
        "name": "Fatima Al-Mansoori",
        "dept": "Bioinformatics",
        "year": "Senior",
        "bio": "Computational biologist analyzing genomic variant data and protein folding structures.",
        "github": "https://github.com/fatima-bioinfo",
        "teach": [
            {"skill": "Statistical Inference", "level": "EXPERT", "exp": 3.5, "desc": "High-dimensional statistical modeling for genomic microarrays."},
            {"skill": "Data Analysis", "level": "ADVANCED", "exp": 3.0, "desc": "Cleaned gigabyte-scale RNA sequence datasets."},
            {"skill": "Scientific Paper Writing", "level": "ADVANCED", "exp": 2.5, "desc": "Published 2 peer-reviewed articles in computational biology journals."},
        ],
        "learn": [
            {"skill": "Deep Learning", "level": "BEGINNER", "desc": "Want to apply AlphaFold and ESM transformers to protein models."},
            {"skill": "Docker Containerization", "level": "BEGINNER", "desc": "Need reproducible computational pipelines for lab experiments."},
        ],
    },
    {
        "email": "diego.santos@university.edu",
        "name": "Diego Santos",
        "dept": "Computer Science",
        "year": "Senior",
        "bio": "Cloud architect and DevOps geek. Maintains the college coding platform infrastructure.",
        "github": "https://github.com/diegosantos-devops",
        "teach": [
            {"skill": "AWS Cloud Architecture", "level": "EXPERT", "exp": 3.0, "desc": "AWS Certified Solutions Architect Associate; deployed ECS clusters."},
            {"skill": "Docker Containerization", "level": "EXPERT", "exp": 3.0, "desc": "Engineered automated container build caching for campus hackathon."},
            {"skill": "CI/CD Pipelines", "level": "ADVANCED", "exp": 2.5, "desc": "Set up GitHub Actions matrix workflows and security scans."},
        ],
        "learn": [
            {"skill": "Go", "level": "BEGINNER", "desc": "Writing custom Kubernetes operators and CLI tools in Golang."},
            {"skill": "GraphQL", "level": "BEGINNER", "desc": "Exploring unified API gateways for campus microservices."},
        ],
    },
    {
        "email": "lucas.muller@university.edu",
        "name": "Lucas Müller",
        "dept": "Robotics Engineering",
        "year": "Masters",
        "bio": "Robotics engineer building autonomous quadrupeds and ROS2 navigation pipelines.",
        "github": "https://github.com/lucas-muller-rob",
        "teach": [
            {"skill": "C++", "level": "EXPERT", "exp": 4.5, "desc": "Modern C++20 authoring for real-time robotic motor controls."},
            {"skill": "Reinforcement Learning", "level": "ADVANCED", "exp": 2.0, "desc": "Trained quadruped gait control in Isaac Gym simulation."},
            {"skill": "Rust", "level": "INTERMEDIATE", "exp": 1.5, "desc": "Embedded firmware development on STM32 microcontrollers."},
        ],
        "learn": [
            {"skill": "Figma Prototyping", "level": "BEGINNER", "desc": "Need to design intuitive tablet control interfaces for our robots."},
            {"skill": "React.js", "level": "BEGINNER", "desc": "Building real-time robot telemetry web interfaces."},
        ],
    },
    {
        "email": "zainab.khalil@university.edu",
        "name": "Zainab Khalil",
        "dept": "Media & Communications",
        "year": "Junior",
        "bio": "Technical communicator and documentary storyteller making engineering research accessible.",
        "github": "https://github.com/zainab-comm",
        "teach": [
            {"skill": "Technical Writing", "level": "EXPERT", "exp": 3.0, "desc": "Lead editor for university engineering research magazine."},
            {"skill": "Public Speaking & Pitch Presentation", "level": "ADVANCED", "exp": 2.5, "desc": "Coached 15 hackathon teams on concise slide narrative arcs."},
            {"skill": "Negotiation & Conflict Resolution", "level": "ADVANCED", "exp": 2.0, "desc": "Certified peer mediator for campus student organizations."},
        ],
        "learn": [
            {"skill": "UI Design & Wireframing", "level": "BEGINNER", "desc": "Want to visually illustrate documentation workflows in wireframes."},
            {"skill": "Data Visualization", "level": "BEGINNER", "desc": "Want to create visual charts for investigative science reports."},
        ],
    },
    {
        "email": "arjun.nair@university.edu",
        "name": "Arjun Nair",
        "dept": "Computer Science",
        "year": "Junior",
        "bio": "Cross-platform mobile developer. Published 2 apps with 10k+ active student downloads.",
        "github": "https://github.com/arjun-nair-dev",
        "teach": [
            {"skill": "Flutter", "level": "EXPERT", "exp": 3.0, "desc": "Built campus shuttle live tracking app with Flutter & Firebase."},
            {"skill": "React Native", "level": "ADVANCED", "exp": 2.0, "desc": "Cross-platform mobile apps with native bridge modules."},
            {"skill": "Mobile Development", "level": "ADVANCED", "exp": 2.5, "desc": "App Store and Google Play publishing and release management."},
        ],
        "learn": [
            {"skill": "FastAPI", "level": "BEGINNER", "desc": "Need to build fast asynchronous backend APIs for my mobile apps."},
            {"skill": "Machine Learning", "level": "BEGINNER", "desc": "Want to integrate on-device smart recommendations."},
        ],
    },
    {
        "email": "sophie.dubois@university.edu",
        "name": "Sophie Dubois",
        "dept": "Economics & Finance",
        "year": "Senior",
        "bio": "Quantitative finance researcher analyzing micro-lending dynamics and fintech inclusion.",
        "github": "https://github.com/sophie-dubois-econ",
        "teach": [
            {"skill": "Financial Modeling", "level": "EXPERT", "exp": 3.0, "desc": "Built student loan amortisation and venture financial models."},
            {"skill": "Data Analysis", "level": "ADVANCED", "exp": 2.5, "desc": "Econometric regression analysis on macro-economic datasets."},
            {"skill": "Statistical Inference", "level": "ADVANCED", "exp": 2.0, "desc": "Time-series forecasting with ARIMA and GARCH models."},
        ],
        "learn": [
            {"skill": "Python", "level": "BEGINNER", "desc": "Transitioning from Excel/Stata to automated Python data stacks."},
            {"skill": "SQL & Relational Modeling", "level": "BEGINNER", "desc": "Need SQL to query database financial ledgers."},
        ],
    },
    {
        "email": "kevin.zhang@university.edu",
        "name": "Kevin Zhang",
        "dept": "Computer Science",
        "year": "Freshman",
        "bio": "Enthusiastic freshman coder eager to learn modern web development and collaborate on projects.",
        "github": "https://github.com/kevinzhang-06",
        "teach": [
            {"skill": "Java", "level": "INTERMEDIATE", "exp": 1.5, "desc": "AP Computer Science A perfect score; data structures coursework."},
            {"skill": "C++", "level": "INTERMEDIATE", "exp": 1.0, "desc": "Competitive programming algorithms on Codeforces."},
        ],
        "learn": [
            {"skill": "Python", "level": "BEGINNER", "desc": "Want to learn Python for hackathons and script automation."},
            {"skill": "Web Development", "level": "BEGINNER", "desc": "Looking for a mentor to learn HTML/CSS/JS and React."},
        ],
    },
    {
        "email": "maya.lin@university.edu",
        "name": "Maya Lin",
        "dept": "Computer Science",
        "year": "Junior",
        "bio": "Full-stack engineer focusing on Next.js, GraphQL, and modern TypeScript architectures.",
        "github": "https://github.com/mayalin-web",
        "teach": [
            {"skill": "Next.js", "level": "EXPERT", "exp": 2.5, "desc": "Architected university events platform handling 50k monthly visits."},
            {"skill": "TypeScript", "level": "ADVANCED", "exp": 3.0, "desc": "Strict type-safety, utility types, and generics master."},
            {"skill": "GraphQL", "level": "ADVANCED", "exp": 2.0, "desc": "Designed clean GraphQL schemas with Apollo Federation."},
        ],
        "learn": [
            {"skill": "Ethical Hacking & Penetration Testing", "level": "BEGINNER", "desc": "Want to learn how to test my web apps for security holes."},
            {"skill": "Docker Containerization", "level": "INTERMEDIATE", "desc": "Looking to containerize multi-service applications."},
        ],
    },
    {
        "email": "hassan.ali@university.edu",
        "name": "Hassan Ali",
        "dept": "Electrical Engineering",
        "year": "Senior",
        "bio": "Hardware hacker and embedded systems developer. Drone and IoT enthusiast.",
        "github": "https://github.com/hassan-ali-ee",
        "teach": [
            {"skill": "Agri-Tech IoT Monitoring", "level": "EXPERT", "exp": 3.0, "desc": "Designed custom PCB sensor nodes with solar harvesting."},
            {"skill": "C++", "level": "ADVANCED", "exp": 3.0, "desc": "Bare-metal microcontroller driver writing."},
            {"skill": "Precision Agriculture & Drones", "level": "INTERMEDIATE", "exp": 1.5, "desc": "Custom flight controller configuration for crop scouting."},
        ],
        "learn": [
            {"skill": "AWS Cloud Architecture", "level": "BEGINNER", "desc": "Need to connect thousands of IoT sensor nodes to AWS IoT Core."},
            {"skill": "Data Visualization", "level": "BEGINNER", "desc": "Want to plot live sensor feeds on web graphs."},
        ],
    },
    {
        "email": "chloe.dupont@university.edu",
        "name": "Chloe Dupont",
        "dept": "Design & Arts",
        "year": "Sophomore",
        "bio": "Graphic and UX designer specializing in design systems and accessible interface design.",
        "github": "https://github.com/chloe-dupont-ui",
        "teach": [
            {"skill": "Design Systems", "level": "ADVANCED", "exp": 2.0, "desc": "Built design tokens and reusable component specs for college portal."},
            {"skill": "UI Design & Wireframing", "level": "ADVANCED", "exp": 2.5, "desc": "WCAG 2.1 AA accessible color palettes and visual balance."},
            {"skill": "Figma Prototyping", "level": "ADVANCED", "exp": 2.0, "desc": "Complex interactive component states and variants."},
        ],
        "learn": [
            {"skill": "Technical Writing", "level": "BEGINNER", "desc": "Want to write clear design documentation and guidelines for devs."},
            {"skill": "Prompt Engineering", "level": "BEGINNER", "desc": "Exploring generative AI image and design workflows."},
        ],
    },
    {
        "email": "joshua.kim@university.edu",
        "name": "Joshua Kim",
        "dept": "Data Science",
        "year": "Junior",
        "bio": "Data engineer specializing in large-scale SQL queries, ETL pipelines, and dashboard design.",
        "github": "https://github.com/joshuakim-data",
        "teach": [
            {"skill": "SQL & Relational Modeling", "level": "EXPERT", "exp": 3.0, "desc": "Optimized complex analytical queries and warehouse schemas."},
            {"skill": "Data Visualization", "level": "ADVANCED", "exp": 2.5, "desc": "Authoring interactive D3 and Plotly dashboards."},
            {"skill": "Python", "level": "ADVANCED", "exp": 2.5, "desc": "Built automated data ingestion pipelines."},
        ],
        "learn": [
            {"skill": "Natural Language Processing", "level": "BEGINNER", "desc": "Want to analyze unstructured customer feedback text."},
            {"skill": "Venture Capital & Pitching", "level": "BEGINNER", "desc": "Working on a data analytics startup idea."},
        ],
    },
    {
        "email": "olivia.taylor@university.edu",
        "name": "Olivia Taylor",
        "dept": "Business Administration",
        "year": "Senior",
        "bio": "Agile coach and project manager. Led student consulting club to 5 corporate client wins.",
        "github": "https://github.com/olivia-taylor-agile",
        "teach": [
            {"skill": "Agile & Scrum Project Management", "level": "EXPERT", "exp": 3.0, "desc": "Certified ScrumMaster (CSM); ran 25+ sprint cycles."},
            {"skill": "Cross-functional Team Leadership", "level": "EXPERT", "exp": 3.0, "desc": "Organized campus hackathon coordinating 60 volunteers."},
            {"skill": "Negotiation & Conflict Resolution", "level": "ADVANCED", "exp": 2.0, "desc": "Contract negotiations with hackathon sponsors."},
        ],
        "learn": [
            {"skill": "Product Management", "level": "INTERMEDIATE", "desc": "Transitioning from scrum master to software product manager."},
            {"skill": "Data Analysis", "level": "BEGINNER", "desc": "Want to interpret A/B experiment telemetry metrics."},
        ],
    },
    {
        "email": "vikram.singh@university.edu",
        "name": "Vikram Singh",
        "dept": "Computer Science",
        "year": "Senior",
        "bio": "Distributed systems engineer working with Go, Docker, and Kubernetes.",
        "github": "https://github.com/vikram-singh-sys",
        "teach": [
            {"skill": "Go", "level": "EXPERT", "exp": 3.0, "desc": "Engineered high-throughput concurrent WebSocket chat server."},
            {"skill": "Kubernetes Orchestration", "level": "ADVANCED", "exp": 2.0, "desc": "Configured multi-tenant staging clusters with cert-manager and ingress."},
            {"skill": "Docker Containerization", "level": "ADVANCED", "exp": 2.5, "desc": "Optimized lightweight Alpine base images for microservices."},
        ],
        "learn": [
            {"skill": "Cybersecurity", "level": "INTERMEDIATE", "desc": "Want to master container runtime security and eBPF monitoring."},
            {"skill": "Rust", "level": "BEGINNER", "desc": "Learning Rust for kernel-level networking experiments."},
        ],
    },
    {
        "email": "fatou.diop@university.edu",
        "name": "Fatou Diop",
        "dept": "Agricultural Sciences",
        "year": "Junior",
        "bio": "Agronomy student researching drought-resistant soil regeneration and biochar.",
        "github": "https://github.com/fatou-diop-agri",
        "teach": [
            {"skill": "Soil Health & Organic Farming", "level": "EXPERT", "exp": 3.0, "desc": "Conducted 2-year field study on biochar water retention."},
            {"skill": "Qualitative Research Methods", "level": "ADVANCED", "exp": 2.0, "desc": "Surveyed 100+ local smallholder farmers on climate adaptation."},
            {"skill": "Literature Review Synthesis", "level": "ADVANCED", "exp": 2.5, "desc": "Comprehensive review paper on tropical agroforestry systems."},
        ],
        "learn": [
            {"skill": "Precision Agriculture & Drones", "level": "BEGINNER", "desc": "Want to map soil moisture variations using aerial sensors."},
            {"skill": "Python", "level": "BEGINNER", "desc": "Need Python to analyze farm soil test results."},
        ],
    },
    {
        "email": "liam.oconnor@university.edu",
        "name": "Liam O'Connor",
        "dept": "Software Engineering",
        "year": "Junior",
        "bio": "Backend software engineer building microservices with Java, Spring, and PostgreSQL.",
        "github": "https://github.com/liam-oconnor-dev",
        "teach": [
            {"skill": "Java", "level": "EXPERT", "exp": 3.5, "desc": "Enterprise Java backend authoring; strong concurrent memory model knowledge."},
            {"skill": "SQL & Relational Modeling", "level": "ADVANCED", "exp": 3.0, "desc": "PostgreSQL indexing, EXPLAIN ANALYZE query tuning, ACID transactions."},
            {"skill": "CI/CD Pipelines", "level": "INTERMEDIATE", "exp": 1.5, "desc": "Maven automated testing and Docker publishing pipelines."},
        ],
        "learn": [
            {"skill": "FastAPI", "level": "BEGINNER", "desc": "Want to learn asynchronous Python for lightweight microservices."},
            {"skill": "AWS Cloud Architecture", "level": "BEGINNER", "desc": "Targeting cloud deployment certification."},
        ],
    },
    {
        "email": "hina.takahashi@university.edu",
        "name": "Hina Takahashi",
        "dept": "Computer Science",
        "year": "Senior",
        "bio": "AI engineer exploring generative AI workflows, prompt optimization, and agentic systems.",
        "github": "https://github.com/hina-takahashi-ai",
        "teach": [
            {"skill": "Prompt Engineering", "level": "EXPERT", "exp": 2.5, "desc": "Designed complex multi-agent reasoning chains with tool calling."},
            {"skill": "Python", "level": "ADVANCED", "exp": 3.0, "desc": "Wrote custom evaluation harnesses for LLM accuracy testing."},
            {"skill": "Natural Language Processing", "level": "ADVANCED", "exp": 2.0, "desc": "RAG vector retrieval indexing with FAISS and Chroma."},
        ],
        "learn": [
            {"skill": "UI Design & Wireframing", "level": "BEGINNER", "desc": "Want to create clean user interfaces for generative AI apps."},
            {"skill": "Public Speaking & Pitch Presentation", "level": "INTERMEDIATE", "desc": "Practicing for upcoming university hackathon pitch."},
        ],
    },
    {
        "email": "andre.silva@university.edu",
        "name": "André Silva",
        "dept": "Telecommunications",
        "year": "Masters",
        "bio": "Network engineer and cryptography enthusiast researching post-quantum security algorithms.",
        "github": "https://github.com/andre-silva-crypto",
        "teach": [
            {"skill": "Cryptography Fundamentals", "level": "EXPERT", "exp": 3.5, "desc": "Lattice-based cryptography and zero-knowledge proofs research."},
            {"skill": "Network Security", "level": "ADVANCED", "exp": 3.0, "desc": "Secure TLS 1.3 protocol implementation and VPN architectures."},
            {"skill": "C++", "level": "ADVANCED", "exp": 3.0, "desc": "Optimized OpenSSL cryptographic primitive bindings."},
        ],
        "learn": [
            {"skill": "Rust", "level": "BEGINNER", "desc": "Porting C++ cryptographic algorithms to safe Rust."},
            {"skill": "Machine Learning", "level": "BEGINNER", "desc": "Interested in ML for anomaly and malware detection."},
        ],
    },
    {
        "email": "gabriella.rossi@university.edu",
        "name": "Gabriella Rossi",
        "dept": "Design & Architecture",
        "year": "Junior",
        "bio": "Spatial designer exploring environmental design and interactive physical computing.",
        "github": "https://github.com/gabi-rossi-design",
        "teach": [
            {"skill": "UX User Research", "level": "ADVANCED", "exp": 2.5, "desc": "Conducted ethnographic field studies on campus study space ergonomics."},
            {"skill": "UI Design & Wireframing", "level": "ADVANCED", "exp": 2.0, "desc": "Visual balance, spatial composition, and accessibility guidelines."},
            {"skill": "Qualitative Research Methods", "level": "ADVANCED", "exp": 2.0, "desc": "Grounded theory analysis of student collaborative behaviors."},
        ],
        "learn": [
            {"skill": "Figma Prototyping", "level": "INTERMEDIATE", "desc": "Want to advance from static wireframes to high-fidelity components."},
            {"skill": "Hydroponics & Vertical Farming", "level": "BEGINNER", "desc": "Designing indoor modular vertical gardens for campus library."},
        ],
    },
    {
        "email": "noah.bernard@university.edu",
        "name": "Noah Bernard",
        "dept": "Computer Science",
        "year": "Senior",
        "bio": "Rust evangelist building high-performance CLI tools and memory-safe network proxies.",
        "github": "https://github.com/noah-bernard-rs",
        "teach": [
            {"skill": "Rust", "level": "EXPERT", "exp": 3.0, "desc": "Built async multithreaded reverse proxy with Tokio in Rust."},
            {"skill": "C++", "level": "ADVANCED", "exp": 3.0, "desc": "Memory management, pointers, and systems programming."},
            {"skill": "Technical Writing", "level": "ADVANCED", "exp": 2.0, "desc": "Author of popular blog series on Rust lifetimes and ownership."},
        ],
        "learn": [
            {"skill": "Web Application Security", "level": "BEGINNER", "desc": "Want to learn ethical exploitation to secure Rust web services."},
            {"skill": "Next.js", "level": "BEGINNER", "desc": "Building documentation landing pages for open source Rust tools."},
        ],
    },
    {
        "email": "kavita.deshmukh@university.edu",
        "name": "Kavita Deshmukh",
        "dept": "Environmental Engineering",
        "year": "Junior",
        "bio": "Environmental engineer passionate about hydroponics, urban sustainability, and renewable energy.",
        "github": "https://github.com/kavita-green",
        "teach": [
            {"skill": "Hydroponics & Vertical Farming", "level": "EXPERT", "exp": 3.0, "desc": "Engineered automated nutrient doser for campus rooftop greenhouse."},
            {"skill": "Soil Health & Organic Farming", "level": "ADVANCED", "exp": 2.5, "desc": "Organic composting and closed-loop nutrient cycling."},
            {"skill": "Experimental Design & A/B Testing", "level": "ADVANCED", "exp": 2.0, "desc": "Controlled trials on nutrient concentration vs crop growth rates."},
        ],
        "learn": [
            {"skill": "Agri-Tech IoT Monitoring", "level": "BEGINNER", "desc": "Want to connect greenhouse pumps to automated microcontroller sensors."},
            {"skill": "Data Analysis", "level": "INTERMEDIATE", "desc": "Analyzing greenhouse yield variance across seasons."},
        ],
    },
    {
        "email": "benjamin.cohen@university.edu",
        "name": "Benjamin Cohen",
        "dept": "Cognitive Science",
        "year": "Masters",
        "bio": "Cognitive scientist researching human-AI collaboration and interactive decision making.",
        "github": "https://github.com/bencohen-cogsci",
        "teach": [
            {"skill": "Experimental Design & A/B Testing", "level": "EXPERT", "exp": 3.5, "desc": "Conducted 15+ behavioral lab experiments with statistical power analysis."},
            {"skill": "Qualitative Research Methods", "level": "ADVANCED", "exp": 2.5, "desc": "In-depth protocol analysis of human problem solving under pressure."},
            {"skill": "Prompt Engineering", "level": "ADVANCED", "exp": 2.0, "desc": "Benchmarked LLM cognitive biases across prompt variations."},
        ],
        "learn": [
            {"skill": "React.js", "level": "BEGINNER", "desc": "Need to build interactive browser experiments for research participants."},
            {"skill": "Python", "level": "INTERMEDIATE", "desc": "Deepening automated analysis of experiment log files."},
        ],
    },
    {
        "email": "aisha.traore@university.edu",
        "name": "Aisha Traoré",
        "dept": "Information Systems",
        "year": "Junior",
        "bio": "Cloud and database administrator. Enthusiastic about cloud migrations and scalable SQL.",
        "github": "https://github.com/aisha-traore-cloud",
        "teach": [
            {"skill": "Microsoft Azure", "level": "ADVANCED", "exp": 2.5, "desc": "Certified Azure Fundamentals & Administrator; managed cloud DB instances."},
            {"skill": "SQL & Relational Modeling", "level": "ADVANCED", "exp": 2.5, "desc": "Designed normalized schemas for student club registration system."},
            {"skill": "CI/CD Pipelines", "level": "INTERMEDIATE", "exp": 1.5, "desc": "Configured Azure DevOps release pipelines for student web projects."},
        ],
        "learn": [
            {"skill": "AWS Cloud Architecture", "level": "BEGINNER", "desc": "Comparing AWS multi-region failover with Azure availability zones."},
            {"skill": "FastAPI", "level": "BEGINNER", "desc": "Learning Python to write serverless cloud functions."},
        ],
    },
    {
        "email": "matthew.park@university.edu",
        "name": "Matthew Park",
        "dept": "Computer Science",
        "year": "Senior",
        "bio": "Game developer and 3D graphics programmer using C# and Unity. VR hackathon winner.",
        "github": "https://github.com/matthewpark-games",
        "teach": [
            {"skill": "C#", "level": "EXPERT", "exp": 4.0, "desc": "Architected multiplayer game mechanics and physics simulations."},
            {"skill": "UI Design & Wireframing", "level": "INTERMEDIATE", "exp": 2.0, "desc": "Designed responsive diegetic HUD interfaces for VR headsets."},
            {"skill": "C++", "level": "INTERMEDIATE", "exp": 2.0, "desc": "Custom shader and rendering pipeline authoring."},
        ],
        "learn": [
            {"skill": "Deep Learning", "level": "BEGINNER", "desc": "Want to generate dynamic NPC game dialog using local LLMs."},
            {"skill": "TypeScript", "level": "BEGINNER", "desc": "Porting game tools to web dashboards with WebGL."},
        ],
    },
    {
        "email": "sara.lindqvist@university.edu",
        "name": "Sara Lindqvist",
        "dept": "Business & Technology",
        "year": "Senior",
        "bio": "Product lead bridging technical engineering teams with business stakeholders.",
        "github": "https://github.com/sara-lindqvist-pm",
        "teach": [
            {"skill": "Product Management", "level": "EXPERT", "exp": 3.0, "desc": "Interned as APM at FinTech unicorn; authored 12 comprehensive PRDs."},
            {"skill": "Cross-functional Team Leadership", "level": "ADVANCED", "exp": 2.5, "desc": "Aligned engineering, design, and legal teams on privacy compliance."},
            {"skill": "Public Speaking & Pitch Presentation", "level": "ADVANCED", "exp": 2.5, "desc": "Frequent presenter at university entrepreneurship panels."},
        ],
        "learn": [
            {"skill": "Data Visualization", "level": "INTERMEDIATE", "desc": "Want to build executive KPI metric dashboards."},
            {"skill": "FastAPI", "level": "BEGINNER", "desc": "Understanding API architecture to better communicate with backend teams."},
        ],
    },
]

PROJECTS_SEED = [
    {
        "owner_email": "ananya.iyer@university.edu",
        "title": "Autonomous AgroDrone Crop Scouting",
        "description": "Building an autonomous drone system that uses multispectral cameras and edge computer vision to detect early weed outbreaks and nutrient deficiencies in university test fields.",
        "category": "Agriculture & Robotics",
        "max_members": 5,
        "requirements": [
            {"skill": "Computer Vision", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Train real-time weed identification model."},
            {"skill": "Precision Agriculture & Drones", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Drone mission planning and GPS waypoint telemetry."},
            {"skill": "Python", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Data pipeline from drone SD card to cloud."},
            {"skill": "UI Design & Wireframing", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Farmer web dashboard for field heatmaps."},
        ],
    },
    {
        "owner_email": "aarav.sharma@university.edu",
        "title": "Campus Peer Learning Exchange Network",
        "description": "Developing a decentralized skill exchange web platform with an internal credit economy, automated matching, and project team formation for 20,000 students.",
        "category": "Web & Social",
        "max_members": 4,
        "requirements": [
            {"skill": "React.js", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Build responsive student dashboard and search views."},
            {"skill": "FastAPI", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Async REST backend with credit ledger."},
            {"skill": "Tailwind CSS", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Professional university UI aesthetic."},
            {"skill": "Figma Prototyping", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Component libraries and user journey flows."},
        ],
    },
    {
        "owner_email": "tariq.mansoor@university.edu",
        "title": "Campus Cyber Range Vulnerability Lab",
        "description": "Creating an isolated virtual laboratory network where students can safely practice ethical penetration testing, defense against attacks, and security logging.",
        "category": "Cybersecurity",
        "max_members": 4,
        "requirements": [
            {"skill": "Ethical Hacking & Penetration Testing", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Design intentionally vulnerable machines and challenges."},
            {"skill": "Docker Containerization", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Containerize vulnerable target environments for automated reset."},
            {"skill": "Network Security", "level": "INTERMEDIATE", "importance": "MANDATORY", "desc": "Isolated VLAN configuration and intrusion detection."},
            {"skill": "Technical Writing", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Write clear walkthrough guides and student writeups."},
        ],
    },
    {
        "owner_email": "samuel.ochieng@university.edu",
        "title": "GreenCart: Zero-Waste Campus Grocery Cooperative",
        "description": "A student-run cooperative platform connecting regional organic farmers with campus dorms to eliminate packaging waste and supply fresh produce at wholesale prices.",
        "category": "Business & Sustainability",
        "max_members": 4,
        "requirements": [
            {"skill": "Product Management", "level": "ADVANCED", "importance": "MANDATORY", "desc": "Customer discovery and operational workflow design."},
            {"skill": "Next.js", "level": "INTERMEDIATE", "importance": "MANDATORY", "desc": "Student ordering storefront with mobile responsiveness."},
            {"skill": "Financial Modeling", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Cooperative member pricing model and logistics cost forecast."},
            {"skill": "Soil Health & Organic Farming", "level": "INTERMEDIATE", "importance": "PREFERRED", "desc": "Farmer vetting and produce quality standards."},
        ],
    },
]
